AWSTemplateFormatVersion: 2010-09-09
Description: Build Infrastructure resources for persisting Terrafrom state files

Parameters:
  identifier:
    Description: The identifier for resources
    Type: String
    Default: tf-state

Resources:
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Sub ${identifier}-${AWS::AccountId}-${AWS::Region}
      Tags:
        - Key: CreatedBy
          Value: Terrafrom

  dynamodbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: LockID
          AttributeType: S
      KeySchema:
        - AttributeName: LockID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: !Sub ${identifier}-lock-${AWS::AccountId}-${AWS::Region}
      Tags:
        - Key: CreatedBy
          Value: Terrafrom
