name: Deploy API

on:
  workflow_dispatch:
    branches:
      - main
      - develop
      - feature/*
      - hotfix/*
      - bugfix/*
    inputs:
      deployment:
        description: Deployment to apply
        type: choice
        options:
          - common_infra
          - api
          - dynamodb
        default: api
        required: true
      environment:
        description: Environment to run agains
        type: choice
        options:
          - dev
        default: dev
        required: true

run-name: Deploy ${{ inputs.deployment }} to ${{ inputs.environment }} environment

permissions:
  contents: read
  pull-requests: write
  id-token: write

env:
  # Env Variables
  ROLE_TO_ASSUME: ${{ vars.ROLE_TO_ASSUME }}
  ROLE_SESSION_NAME: ${{ vars.ROLE_SESSION_NAME }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  STATE_BUCKET: ${{ vars.STATE_BUCKET }}
  # Input Variables
  ENVIRONMENT: ${{ inputs.environment }}
  NICKNAME: todo
  TF_VERSION: 1.8.0
  WORKING_DIRECTORY: terraform/deployments/${{ inputs.deployment }}
  # Terraform Variables are prefixed with TF_VAR
  TF_VAR_aws_region: ${{ vars.AWS_REGION }}

jobs:
  terraform-plan-apply:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      #this is needed since we are running terraform with read-only permissions
      ARM_SKIP_PROVIDER_REGISTRATION: true
      TF_VAR_app_version: ${{ steps.custom-tag.outputs.app_version }}
    outputs:
      exitcode: ${{ steps.tf-plan.outputs.exitcode }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read Customize Version
        id: custom-tag
        run: |
          app_version = $(cat VERSION.txt)
          echo $app_version
          echo "app_version=$app_version" >> $GITHUB_OUTPUT

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          role-session-name: ${{ env.ROLE_SESSION_NAME }}
          aws-region: ${{ env.AWS_REGION }}
      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          terraform init -reconfigure \
          -backend-config="bucket=$STATE_BUCKET" \
          -backend-config="region=$AWS_REGION" \
          -backend-config="key=$NICKNAME/$ENVIRONMENT/$AWS_REGION/terraform.tfstate"

      # Generates an execution plan for Terraform
      # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
      - name: Terraform Plan
        id: tf-plan
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          set +e # allow the workflow to continue following steps even if the `terraform` execution failed

          terraform plan -var-file $(pwd)/../../settings/$ENVIRONMENT/terraform.tfvars \
          -detailed-exitcode -no-color -out tfplan

          exitcode=$?
          echo exitcode = $exitcode

          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT

          if [ $exitcode -eq 1 ]; then
            echo Terraform Plan Failed!
            exit 1
          else
            exit 0
          fi

      # Create string output of Terraform Plan
      - name: Create String Output
        id: tf-plan-string
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          TERRAFORM_PLAN=$(terraform show -no-color tfplan)

          delimiter="$(openssl rand -hex 8)"
          echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
          echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
          echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo '```terraform' >> $GITHUB_OUTPUT
          echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
          echo '```' >> $GITHUB_OUTPUT
          echo "</details>" >> $GITHUB_OUTPUT
          echo "${delimiter}" >> $GITHUB_OUTPUT

      # Publish Terraform Plan as task summary
      - name: Publish Terraform Plan to Task Summary
        env:
          SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
        run: |
          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY

      - name: Terraform Apply
        if: ${{ steps.tf-plan.outputs.exitcode == 2 }}
        id: tf-apply-string
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          TERRAFORM_OUTPUT=$(terraform apply -auto-approve tfplan -no-color)

          delimiter="$(openssl rand -hex 8)"
          echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
          echo "### Terraform Apply Output" >> $GITHUB_OUTPUT
          echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo '```terraform' >> $GITHUB_OUTPUT
          echo "$TERRAFORM_OUTPUT" >> $GITHUB_OUTPUT
          echo '```' >> $GITHUB_OUTPUT
          echo "</details>" >> $GITHUB_OUTPUT
          echo "${delimiter}" >> $GITHUB_OUTPUT

      - name: Publish Terraform Output to Task Summary
        if: ${{ steps.tf-plan.outputs.exitcode == 2 }}
        env:
          SUMMARY: ${{ steps.tf-apply-string.outputs.summary }}
        run: |
          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
