name: Plan & Apply

on:
  workflow_dispatch:
    branches:
      - main
      - develop
      - feature/*
      - hotfix/*
      - bugfix/*
    inputs:
      deployment:
        description: Deployment to apply
        type: choice
        options:
          - common_infra
          - api
          - dynamodb
        default: api
        required: true
      environment:
        description: Environment to run against
        type: choice
        options:
          - dev
        default: dev
        required: true

run-name: Deploy ${{ inputs.deployment }} to ${{ inputs.environment }} environment

permissions:
  contents: read
  id-token: write

jobs:
  plan-apply:
    uses: ./.github/workflows/deploy_reusable.yaml
    with:
      environment: ${{ inputs.environment }}
      deployment: ${{ inputs.deployment }}
