name: Plan Destroy & Apply

on:
  workflow_dispatch:
    branches:
      - main
      - develop
      - feature/*
      - hotfix/*
      - bugfix/*
    inputs:
      deployment:
        description: Deployment to apply
        type: choice
        options:
          - common_infra
          - api
          - dynamodb
        default: api
        required: true
      environment:
        description: Environment to run against
        type: choice
        options:
          - dev
        default: dev
        required: true

run-name: Destroy ${{ inputs.deployment }} from ${{ inputs.environment }} environment

jobs:
  plan-apply:
    uses: .github/workflows/deploy_reusable.yaml
    with:
      environment: ${{ inputs.environment }}
      is_destroy: true
      working-directory: terraform/deployments/${{ inputs.deployment }}
