name: Terragrunt Unit Deploy

on:
  workflow_dispatch:
    inputs:
      unit:
        description: Terragrunt unit to apply
        type: choice
        options:
          - security
          - dynamodb
          - api
        default: api
        required: true
      environment:
        description: Environment to run against
        type: choice
        options:
          - dev
        default: dev
        required: true

run-name: Deploy ${{ inputs.unit }} to ${{ inputs.environment }} environment

permissions:
  contents: read
  id-token: write

jobs:
  deploy-unit:
    name: Deploy Terragrunt Unit
    uses: ./.github/workflows/reusable-terragrunt-deploy.yml
    with:
      environment: ${{ inputs.environment }}
      unit: ${{ inputs.unit }}
