name: Terragrunt Unit Destroy

on:
  workflow_dispatch:
    inputs:
      unit:
        description: Terragrunt unit to destroy
        type: choice
        options:
          - api
          - dynamodb
          - security
        default: api
        required: true
      environment:
        description: Environment to run against
        type: choice
        options:
          - dev
        default: dev
        required: true

run-name: Destroy ${{ inputs.unit }} from ${{ inputs.environment }} environment

permissions:
  actions: read
  contents: read
  id-token: write

jobs:
  destroy-unit:
    name: Destroy
    uses: ./.github/workflows/reusable-terragrunt-deploy.yml
    with:
      environment: ${{ inputs.environment }}
      is_destroy: true
      unit: ${{ inputs.unit }}
